// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY7xnMyYgPBEY530LDHScm0n2cApAflR4',
    appId: '1:408422406740:web:62d437da6afe9995ceabc1',
    messagingSenderId: '408422406740',
    projectId: 'pharmacy-inventory-manag-35681',
    authDomain: 'pharmacy-inventory-manag-35681.firebaseapp.com',
    storageBucket: 'pharmacy-inventory-manag-35681.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA4J5a_YJaf48hthx-JES5ADKnSgb34AA',
    appId: '1:408422406740:android:cd7da085e957a44fceabc1',
    messagingSenderId: '408422406740',
    projectId: 'pharmacy-inventory-manag-35681',
    storageBucket: 'pharmacy-inventory-manag-35681.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY7xnMyYgPBEY530LDHScm0n2cApAflR4',
    appId: '1:408422406740:web:d9bfed6c0c8b5769ceabc1',
    messagingSenderId: '408422406740',
    projectId: 'pharmacy-inventory-manag-35681',
    authDomain: 'pharmacy-inventory-manag-35681.firebaseapp.com',
    storageBucket: 'pharmacy-inventory-manag-35681.appspot.com',
  );
}
